# Generated by Django 4.2.2 on 2023-06-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamePackage',
            new_name='AppPackage',
        ),
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('developerAddress', models.TextField()),
                ('summary', models.TextField()),
                ('installs', models.IntegerField()),
                ('score', models.FloatField()),
                ('ratings', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('developerId', models.IntegerField()),
                ('version', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('icon', models.URLField()),
                ('developerWebsite', models.URLField()),
                ('privacyPolicy', models.URLField()),
                ('genre', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('free', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('app_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_package', to='play_store.apppackage')),
            ],
        ),
        migrations.CreateModel(
            name='AppComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('app_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_details', to='play_store.appdetails')),
            ],
        ),
    ]
