# Generated by Django 4.2.2 on 2023-06-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_store', '0002_rename_gamepackage_apppackage_appdetails_appcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetails',
            name='developerId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='ratings',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='reviews',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='score',
            field=models.CharField(max_length=100),
        ),
    ]
