# Generated by Django 4.2.2 on 2023-06-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_store', '0004_alter_appdetails_installs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='install_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='developer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='developerAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='developerId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='developerWebsite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='installs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='privacyPolicy',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='reviews',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetails',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
